<?php

/**
 * @file
 * Contains Drupal\group_core_comments\group_core_comments.module
 */

use Drupal\group\Entity\Group;
use Drupal\group\Entity\GroupInterface;
use Drupal\group\Entity\GroupContentType;
use Drupal\node\NodeInterface;
use Drupal\node\Entity\NodeType;
use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Database\Database;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_entity_type_alter().
 */
function group_core_comments_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['comment'])) {
    $class = 'Drupal\group_core_comments\GroupCommentAccessControlHandler';
    $entity_types['comment']->setAccessClass($class);
  }
}

///**
// * Implements hook_ENTITY_TYPE_access().
// */
//function group_core_comments_comment_access(\Drupal\Core\Entity\EntityInterface $entity, $operation, \Drupal\Core\Session\AccountInterface $account) {
//  kint($entity);
//
//}
//
///**
// * Implements hook_ENTITY_TYPE_create_access().
// */
//function group_core_comments_comment_create_access(\Drupal\Core\Session\AccountInterface $account, array $context, $entity_bundle) {
//  // No opinion.
//  return AccessResult::neutral();
//}

