<?php

/**
 * @file
 * API functions to manipulate messages.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Element;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\message\Entity\Message;
use Drupal\message\Entity\MessageTemplate;

/**
 * Implements hook_entity_delete().
 *
 * Handles messages deletion when referenced entities are being deleted.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The entity object for the entity that has been deleted.
 */
function message_entity_delete(EntityInterface $entity) {
  $type = $entity->getEntityType()->id();
  if ($type == 'message') {
    // Why not message?
    return;
  }

  $types = \Drupal::config('message.settings')->get('delete_on_entity_delete');

  if (!$types || !in_array($type, $types)) {
    return;
  }

  // List of messages to delete.
  $deletable_mids = [];
  // List of messages that might be deleted;
  // Messages with references to fields with multiple cardinality will be stored
  // in $check_mids in order to check if the entity being deleted is the last
  // one referenced by a given field.
  // Keyed by message ID, pointing to array of the relevant field names.
  $check_mids = [];

  $fields_ids = \Drupal::entityQuery('field_storage_config')->execute();
  /** @var FieldStorageConfig[] $fields */
  $fields = entity_load_multiple('field_storage_config', array_keys($fields_ids));

  // Search for fields in which messages referenced the deleted entity.
  foreach ($fields as $field) {
    if ($field->get('entity_type') != 'message') {
      // This field isn't used in any message.
      continue;
    }

    // Only delete messages due to referenced entity or referenced taxonomy term
    // deletion.
    if ($field->getType() != 'entity_reference') {
      continue;
    }

    $query = \Drupal::entityQuery('message');
    $results = $query
      ->condition($field->getName(), $entity->id())
      ->execute();

    if (empty($results)) {
      continue;
    }

    if ($field->getCardinality() == 1) {
      $deletable_mids += array_keys($results);
    }
    else {
      $messages = Message::loadMultiple($results);

      foreach ($messages as $message) {
        $check_mids[$message->id()][] = $field->getName();
      }
    }
  }

  // Check messages with multiple cardinality references; Only delete such
  // messages if the entity being deleted is the last one referenced by the
  // message.
  if ($check_mids) {
    $messages = Message::loadMultiple(array_keys($check_mids));
    foreach ($messages as $message) {
      foreach ($check_mids[$message->id()] as $field_name) {

        // We need to check if the field is references is empty.
        if (count($message->get($field_name)->referencedEntities()) === 0) {
          $deletable_mids[] = $message->id();
        }
      }
    }
  }

  if ($deletable_mids) {
    // Delete messages.
    $messages = Message::loadMultiple($deletable_mids);
    Message::deleteMultiple($messages);
  }
}

/**
 * Implements hook_cron().
 *
 * Fetch all message templates and purge old messages.
 */
function message_cron() {
  /** @var \Drupal\message\MessagePurgeOrchestrator $purge_orchestrator */
  $purge_orchestrator = \Drupal::service('message.purge_orchestrator');
  $purge_orchestrator->purgeAllTemplateMessages();
}


/**
 * usort callback; Order the form elements by their weight.
 */
function message_order_text_weight($a, $b) {
  if ($a['_weight'] == $b['_weight']) {
    return 0;
  }

  return ($a['_weight'] < $b['_weight']) ? -1 : 1;
}

/**
 * Implement hook_entity_extra_field_info().
 */
function message_entity_extra_field_info() {
  $extra = [];

  /** @var MessageTemplate[] $bundles */
  $bundles = MessageTemplate::loadMultiple();
  foreach ($bundles as $bundle) {

    foreach (array_keys($bundle->getText()) as $delta) {

      if (!is_int($delta)) {
        // The get text holds also the translated text. Since we hold only need
        // the number of partials we don't need to include delta of texts.
        continue;
      }

      $params = ['%number' => $delta];
      $extra['message'][$bundle->id()]['display']['partial_' . $delta] = [
        'label' => t('Partial %number', $params),
        'description' => t('Holds the partial text at position %number', $params),
        'weight' => 0,
      ];
    }
  }

  return $extra;
}

/**
 * Implements hook_config_translation_info_alter().
 */
function message_config_translation_info_alter(&$info) {
  $info['message_template']['class'] = '\Drupal\message\MessageConfigEntityMapper';
}

/**
 * Implements hook_theme().
 */
function message_theme() {
  return [
    'message' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for message templates.
 *
 * Default template: message.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 *   - message: The message object.
 *   - view_mode: View mode; e.g., 'full', 'teaser', etc.
 */
function template_preprocess_message(&$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];

  // Provide a distinct $teaser boolean.
  $variables['teaser'] = $variables['view_mode'] == 'teaser';
  $variables['message'] = $variables['elements']['#message'];

  /** @var \Drupal\message\MessageInterface $message */
  $message = $variables['message'];
  $variables['date'] = drupal_render($variables['elements']['created']);
  unset($variables['elements']['created']);
  $variables['author_name'] = drupal_render($variables['elements']['uid']);
  unset($variables['elements']['uid']);

  $variables['url'] = $message->url('canonical', [
    'language' => $message->language(),
  ]);

  // The 'page' variable is set to TRUE in two occasions:
  //   - The view mode is 'full' and we are on the 'message.view' route.
  //   - The message is in preview and view mode is either 'full' or 'default'.
  $variables['page'] = ($variables['view_mode'] == 'full' || $variables['view_mode'] == 'default');

  // Helpful $content variable for templates.
  $variables += ['content' => []];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function message_theme_suggestions_message(array $variables) {
  $suggestions = [];

  /** @var \Drupal\message\MessageInterface $message */
  $message = $variables['elements']['#message'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'message__' . $sanitized_view_mode;
  $suggestions[] = 'message__' . $message->bundle();
  $suggestions[] = 'message__' . $message->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'message__' . $message->id();
  $suggestions[] = 'message__' . $message->id() . '__' . $sanitized_view_mode;

  return $suggestions;
}
